[package]
name = "perpetuity_sui"
edition = "2024.beta"

[dependencies]
One = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/one-framework", rev = "main" }

[addresses]
perpetuity_sui = "0x0"

[dev-dependencies]

[dev-addresses]